# Generated by Django 4.2.14 on 2024-07-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoices", models.DecimalField(decimal_places=2, max_digits=32)),
                ("deposits", models.DecimalField(decimal_places=2, max_digits=32)),
                ("withdrawals", models.DecimalField(decimal_places=2, max_digits=32)),
                ("date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoices", models.DecimalField(decimal_places=2, max_digits=32)),
                ("deposits", models.DecimalField(decimal_places=2, max_digits=32)),
                ("withdrawals", models.DecimalField(decimal_places=2, max_digits=32)),
                ("date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoices", models.DecimalField(decimal_places=2, max_digits=32)),
                ("deposits", models.DecimalField(decimal_places=2, max_digits=32)),
                ("withdrawals", models.DecimalField(decimal_places=2, max_digits=32)),
                ("date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
