# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0003_initial"),
        ("users", "0001_initial"),
        ("tokens", "0001_initial"),
        ("globals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="数量"
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=32,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "no",
                    models.CharField(max_length=64, unique=True, verbose_name="编号"),
                ),
                (
                    "to",
                    common.fields.ChecksumAddressField(
                        db_index=True, max_length=42, verbose_name="收币地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.player",
                        verbose_name="用户",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globals.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tokens.token",
                        verbose_name="代币",
                    ),
                ),
                (
                    "transaction_queue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.transactionqueue",
                        verbose_name="执行队列",
                    ),
                ),
            ],
            options={
                "verbose_name": "提币",
                "verbose_name_plural": "提币",
            },
        ),
    ]
