# Generated by Django 4.2.14 on 2024-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0007_alter_historicalproject_name_alter_project_name"),
        ("withdrawals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="no",
            field=models.CharField(max_length=64, verbose_name="编号"),
        ),
        migrations.AlterUniqueTogether(
            name="withdrawal",
            unique_together={("project", "no")},
        ),
    ]
