# Generated by Django 4.2.14 on 2024-08-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawals", "0005_alter_withdrawal_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="worth",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="价值(USD)"
            ),
        ),
    ]
