# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0004_initial"),
        ("deposits", "0001_initial"),
        ("tokens", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.player",
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tokens.token",
                verbose_name="代币",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.transaction",
                verbose_name="交易",
            ),
        ),
    ]
