# Generated by Django 4.2.14 on 2024-07-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="project",
        ),
    ]
