volumes:
  production_redis_data: { }
  production_postgres_data: { }
  production_postgres_data_backups: { }

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: evmx_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env
    environment:
      POSTGRES_DB: evmx

  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: evmx_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    ports:
      - '127.0.0.1:9527:8000'
    healthcheck:
      test: [ "CMD", "timeout", "5", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8000 || exit 1" ]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 30s
    command: /start

  monitoring:
    <<: *django
    image: evmx_production_monitoring
    depends_on:
      django:
        condition: service_healthy
    ports: [ ]
    restart: always
    command: /start-monitoring

  celeryworker:
    <<: *django
    image: evmx_production_celeryworker
    depends_on:
      django:
        condition: service_healthy
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: evmx_production_celerybeat
    depends_on:
      - celeryworker
    ports: [ ]
    command: /start-celerybeat
