volumes:
  production_redis_data: { }
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_django_media: { }
  production_django_static: { }

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: evmx_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env
    environment:
      POSTGRES_DB: evmx

  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: evmx_django
    volumes:
      - production_django_media:/app/evmx/media
      - production_django_static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    healthcheck:
      test: [ "CMD", "timeout", "1", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8000 || exit 1" ]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 30s
    command: /start

  celeryworker:
    <<: *django
    image: evmx_celeryworker
    depends_on:
      django:
        condition: service_healthy
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: evmx_celerybeat
    depends_on:
      - celeryworker
    command: /start-celerybeat

  monitoring:
    <<: *django
    image: evmx_monitoring
    depends_on:
      - celerybeat
    restart: always
    command: /start-monitoring

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: evmx_nginx
    depends_on:
      - monitoring
    ports:
      - '0.0.0.0:9527:80'
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
      - production_django_static:/usr/share/nginx/staticfiles:ro
