# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("globals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="系统账单号",
                    ),
                ),
                (
                    "out_no",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="商户账单号",
                    ),
                ),
                ("subject", models.CharField(max_length=32, verbose_name="标题")),
                ("detail", models.JSONField(default=dict, verbose_name="详情")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="应付数量"
                    ),
                ),
                ("expired_time", models.DateTimeField(verbose_name="支付截止时间")),
                (
                    "redirect_url",
                    models.URLField(blank=True, verbose_name="支付成功后重定向地址"),
                ),
                (
                    "salt",
                    models.CharField(max_length=66, unique=True, verbose_name="盐"),
                ),
                ("init_code", models.TextField(verbose_name="合约初始化代码")),
                (
                    "pay_address",
                    common.fields.ChecksumAddressField(
                        db_index=True, max_length=42, verbose_name="账单支付地址"
                    ),
                ),
                (
                    "collection_address",
                    common.fields.ChecksumAddressField(
                        db_index=True, max_length=42, verbose_name="资金归集地址"
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="支付完成")),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        max_digits=32,
                        verbose_name="实际支付数量",
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=32,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.chain",
                        verbose_name="网络",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globals.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=36, verbose_name="支付数量"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                        verbose_name="账单",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.transaction",
                        verbose_name="交易",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
                "ordering": ("transaction",),
            },
        ),
    ]
