# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("tokens", "0001_initial"),
        ("chains", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tokens.token",
                verbose_name="代币",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transaction_queue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.transactionqueue",
                verbose_name="归集交易",
            ),
        ),
    ]
