# Generated by Django 4.2.14 on 2024-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[("contract", "合约"), ("differ", "差额")],
                default="contract",
                max_length=16,
                verbose_name="类型",
            ),
        ),
    ]
