# Generated by Django 4.2.14 on 2024-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0007_alter_historicalproject_name_alter_project_name"),
        ("invoices", "0003_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="expired",
            field=models.BooleanField(default=False, verbose_name="过期未支付"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="original_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="当类型为Differ的时候，最初的期望应付数量",
                max_digits=32,
                null=True,
                verbose_name="原应付数量",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="init_code",
            field=models.TextField(blank=True, verbose_name="合约初始化代码"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="out_no",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="商户账单号"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="salt",
            field=models.CharField(
                blank=True, max_length=66, unique=True, verbose_name="盐"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("project", "out_no")},
        ),
    ]
