# Generated by Django 4.2.14 on 2024-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0007_alter_historicalproject_name_alter_project_name"),
        ("invoices", "0005_rename_no_invoice_sys_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="out_no",
            new_name="no",
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("project", "no")},
        ),
    ]
