# Generated by Django 4.2.14 on 2024-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_rename_out_no_invoice_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="no",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="商户单号"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sys_no",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="系统单号"
            ),
        ),
    ]
