# Generated by Django 4.2.14 on 2024-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_alter_invoice_no_alter_invoice_sys_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="actual_value",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="如果类型为Contract合约,实收数量可能大于应付数量.",
                max_digits=32,
                verbose_name="实收数量",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="original_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="通过接口创建账单的时候,参数中最初期望的应付数量value",
                max_digits=32,
                null=True,
                verbose_name="原始数量",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="value",
            field=models.DecimalField(
                decimal_places=8,
                help_text="如果类型为Differ差额,应付数量可能在原始数量上下差额浮动.",
                max_digits=32,
                verbose_name="应付数量",
            ),
        ),
    ]
