# Generated by Django 4.2.14 on 2024-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_alter_collectionaddressfordiffer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="init_code",
            field=models.TextField(
                blank=True, null=True, verbose_name="合约初始化代码"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="salt",
            field=models.CharField(
                blank=True, max_length=66, null=True, unique=True, verbose_name="盐"
            ),
        ),
    ]
