# Generated by Django 4.2.14 on 2024-07-28 14:48

from django.db import migrations

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_alter_invoice_init_code_alter_invoice_salt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="expired",
        ),
        migrations.AlterField(
            model_name="collectionaddressfordiffer",
            name="address",
            field=common.fields.ChecksumAddressField(
                db_index=True, max_length=42, unique=True, verbose_name="地址"
            ),
        ),
    ]
