# Generated by Django 4.2.14 on 2024-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0013_alter_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[("differ", "差额"), ("contract", "合约")],
                max_length=16,
                verbose_name="类型",
            ),
        ),
    ]
