# Generated by Django 4.2.14 on 2024-08-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0014_alter_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="actual_value",
            field=models.DecimalField(
                decimal_places=18,
                default=0,
                help_text="如果类型为Contract合约,实收数量可能大于应付数量.",
                max_digits=36,
                verbose_name="实收数量",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="original_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="通过接口创建账单的时候,参数中最初期望的应付数量value",
                max_digits=36,
                null=True,
                verbose_name="原始数量",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="value",
            field=models.DecimalField(
                decimal_places=18,
                help_text="如果类型为Differ差额,应付数量可能在原始数量上下差额浮动.",
                max_digits=36,
                verbose_name="应付数量",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="worth",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="价值(USD)"
            ),
        ),
    ]
