# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0004_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("globals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="system_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="提币时,系统通过此账户发送代币到用户地址;要保证此地址的 Gas 和各代币充盈,否则提币无法成功;",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chains.account",
                verbose_name="系统账户",
            ),
        ),
    ]
