# Generated by Django 4.2.14 on 2024-07-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="active",
            field=models.BooleanField(default=True, verbose_name="启用"),
        ),
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True, verbose_name="启用"),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="name",
            field=models.CharField(
                db_index=True, default="默认项目", max_length=255, verbose_name="名称"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="webhook",
            field=models.URLField(
                help_text="用于本网关发送通知到项目后端;",
                max_length=256,
                verbose_name="通知地址",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                default="默认项目", max_length=255, unique=True, verbose_name="名称"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="webhook",
            field=models.URLField(
                help_text="用于本网关发送通知到项目后端;",
                max_length=256,
                verbose_name="通知地址",
            ),
        ),
    ]
