# Generated by Django 4.2.14 on 2024-07-22 08:44

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0005_alter_account_options"),
        ("globals", "0003_historicalproject_active_project_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="appid",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="collection_address",
            field=common.fields.ChecksumAddressField(
                db_index=True,
                help_text="用户支付和充值的代币,将自动归集到此地址;",
                max_length=42,
                verbose_name="代币归集地址",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="gather_time",
            field=models.PositiveIntegerField(
                blank=True,
                default=32,
                help_text="某充币地址中,若某代币大于此周期未进行归集操作,则自动归集;",
                verbose_name="自动归集周期(日)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                help_text="某充币地址中,若某代币的价值大于此,则自动归集;",
                max_digits=10,
                verbose_name="自动归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="hmac_key",
            field=models.CharField(
                blank=True,
                help_text="用于本网关接口签名;",
                max_length=256,
                verbose_name="HMAC密钥",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="ip_white_list",
            field=models.TextField(
                help_text="只有符合白名单的 IP 才可以与本网关交互;支持 IP 地址或 IP 网段;可同时设置多个,中间用英文逗号','分割;",
                verbose_name="IP白名单",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="minimal_gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="某充币地址中,若某代币的价值小于此,即使满足自动归集的条件,也不会执行归集操作;此值是为了防止Gas成本大于归集代币的价值;",
                max_digits=10,
                verbose_name="最小归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="项目名称"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="notification_failed_times",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="通知失败数"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="appid",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="collection_address",
            field=common.fields.ChecksumAddressField(
                db_index=True,
                help_text="用户支付和充值的代币,将自动归集到此地址;",
                max_length=42,
                verbose_name="代币归集地址",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gather_time",
            field=models.PositiveIntegerField(
                blank=True,
                default=32,
                help_text="某充币地址中,若某代币大于此周期未进行归集操作,则自动归集;",
                verbose_name="自动归集周期(日)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                help_text="某充币地址中,若某代币的价值大于此,则自动归集;",
                max_digits=10,
                verbose_name="自动归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="hmac_key",
            field=models.CharField(
                blank=True,
                help_text="用于本网关接口签名;",
                max_length=256,
                verbose_name="HMAC密钥",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ip_white_list",
            field=models.TextField(
                help_text="只有符合白名单的 IP 才可以与本网关交互;支持 IP 地址或 IP 网段;可同时设置多个,中间用英文逗号','分割;",
                verbose_name="IP白名单",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="minimal_gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="某充币地址中,若某代币的价值小于此,即使满足自动归集的条件,也不会执行归集操作;此值是为了防止Gas成本大于归集代币的价值;",
                max_digits=10,
                verbose_name="最小归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="项目名称"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="notification_failed_times",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="通知失败数"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="system_account",
            field=models.OneToOneField(
                blank=True,
                help_text="提币时,系统通过此账户发送代币到用户地址;要保证此地址的 Gas 和各代币充盈,否则提币无法成功;",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project",
                to="chains.account",
                verbose_name="系统账户",
            ),
        ),
    ]
