# Generated by Django 4.2.14 on 2024-07-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0004_alter_historicalproject_appid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ("id",),
                "verbose_name": "项目配置",
                "verbose_name_plural": "项目配置",
            },
        ),
    ]
