# Generated by Django 4.2.14 on 2024-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0006_historicalproject_owner_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="name",
            field=models.CharField(
                db_index=True, max_length=16, verbose_name="项目名称"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=16, unique=True, verbose_name="项目名称"),
        ),
    ]
