# Generated by Django 4.2.14 on 2024-07-27 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("globals", "0007_alter_historicalproject_name_alter_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
                verbose_name="项目人",
            ),
            preserve_default=False,
        ),
    ]
