# Generated by Django 4.2.14 on 2024-07-30 02:28

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0006_alter_transaction_block"),
        ("globals", "0009_alter_historicalproject_owner_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="collection_address",
            field=common.fields.ChecksumAddressField(
                db_index=True,
                help_text="1.充值代币 2.合约支付,将自动归集到此地址; 差额支付地址需要去后台支付栏目单独设置;",
                max_length=42,
                verbose_name="代币归集地址",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="ip_white_list",
            field=models.TextField(
                help_text="只有符合白名单的 IP 才可以与本网关交互; 支持 IP 地址或 IP 网段; 可同时设置多个,中间用英文逗号','分割;",
                verbose_name="IP白名单",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="minimal_gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="充币地址中,若某代币的价值小于此,即使满足自动归集的条件,也不会执行归集操作; 此值是为了防止Gas成本大于归集代币的价值;",
                max_digits=10,
                verbose_name="最小归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="system_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="提币时,系统通过此账户发送代币到用户地址; 要保证此地址的 Gas 和各代币充盈,否则提币无法成功;",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chains.account",
                verbose_name="系统账户",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="collection_address",
            field=common.fields.ChecksumAddressField(
                db_index=True,
                help_text="1.充值代币 2.合约支付,将自动归集到此地址; 差额支付地址需要去后台支付栏目单独设置;",
                max_length=42,
                verbose_name="代币归集地址",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ip_white_list",
            field=models.TextField(
                help_text="只有符合白名单的 IP 才可以与本网关交互; 支持 IP 地址或 IP 网段; 可同时设置多个,中间用英文逗号','分割;",
                verbose_name="IP白名单",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="minimal_gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="充币地址中,若某代币的价值小于此,即使满足自动归集的条件,也不会执行归集操作; 此值是为了防止Gas成本大于归集代币的价值;",
                max_digits=10,
                verbose_name="最小归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="system_account",
            field=models.OneToOneField(
                blank=True,
                help_text="提币时,系统通过此账户发送代币到用户地址; 要保证此地址的 Gas 和各代币充盈,否则提币无法成功;",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project",
                to="chains.account",
                verbose_name="系统账户",
            ),
        ),
    ]
