# Generated by Django 4.2.14 on 2024-07-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0011_alter_historicalproject_owner_alter_project_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalProject",
        ),
    ]
