# Generated by Django 4.2.14 on 2024-08-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0012_delete_historicalproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                help_text="某充币地址中,若某代币的价值大于此,则自动归集;",
                max_digits=16,
                verbose_name="自动归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="minimal_gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="充币地址中,若某代币的价值小于此,即使满足自动归集的条件,也不会执行归集操作; 此值是为了防止Gas成本大于归集代币的价值;",
                max_digits=16,
                verbose_name="最小归集价值(USD)",
            ),
        ),
    ]
