# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("globals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="globals.project",
                verbose_name="项目",
            ),
        ),
    ]
