# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tokens", "0001_initial"),
        ("chains", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalchain",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tokens.token",
                verbose_name="原生币",
            ),
        ),
    ]
