# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalchain",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chain",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chains_as_currency",
                to="tokens.token",
                verbose_name="原生币",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
                verbose_name="公链",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.block",
                verbose_name="父区块",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionqueue",
            unique_together={("account", "chain", "nonce")},
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("chain", "number")},
        ),
    ]
