# Generated by Django 4.2.14 on 2024-07-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0005_alter_account_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="chains.block",
                verbose_name="区块",
            ),
        ),
    ]
