# Generated by Django 4.2.14 on 2024-07-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0006_alter_transaction_block"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalChain",
        ),
    ]
