# Generated by Django 4.2.14 on 2024-07-21 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0004_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltokenaddress",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltokenaddress",
            name="token",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tokens.token",
                verbose_name="代币",
            ),
        ),
        migrations.AddField(
            model_name="historicaltoken",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chains.account"
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chains.chain"
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tokens.token"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tokenaddress",
            unique_together={("token", "chain")},
        ),
        migrations.AlterUniqueTogether(
            name="balance",
            unique_together={("account", "chain", "token")},
        ),
    ]
