# Generated by Django 4.2.14 on 2024-07-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0005_alter_account_options"),
        ("tokens", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokentransfer",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_transfer_obj",
                to="chains.transaction",
            ),
        ),
    ]
