# Generated by Django 4.2.14 on 2024-07-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0004_alter_balance_account_alter_balance_chain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltokenaddress",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="historicaltokenaddress",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltokenaddress",
            name="token",
        ),
        migrations.DeleteModel(
            name="HistoricalToken",
        ),
        migrations.DeleteModel(
            name="HistoricalTokenAddress",
        ),
    ]
