# Generated by Django 4.2.14 on 2024-08-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0005_remove_historicaltokenaddress_chain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="price_in_usd",
            field=models.DecimalField(
                decimal_places=18, default=0, max_digits=36, verbose_name="价格(USD)"
            ),
        ),
    ]
